import { Project } from './types';

export const projects: Project[] = [
  {
    name: 'bluebanc',
    category: 'react-active',
    stack: 'Vite + React + TS',
    description: 'Banking/Fintech application',
    github: 'https://github.com/MattybotStew/bluebanc',
    lastCommit: '2026-07-25',
    buildStatus: 'pass',
  },
  {
    name: 'Eliet',
    category: 'react-active',
    stack: 'Vite + React',
    description: 'Modern brand website with animations',
    github: 'https://github.com/MattybotStew/Eliet',
    lastCommit: '2026-07-24',
    buildStatus: 'pass',
  },
  {
    name: 'shan es-rib-shack',
    category: 'react-active',
    stack: 'Next.js + TS',
    description: 'Restaurant website — original version',
    github: 'https://github.com/MattybotStew/shanes-rib-shack',
    lastCommit: '2026-07-23',
    buildStatus: 'pass',
  },
  {
    name: 'shan es-rib-shack-new',
    category: 'react-active',
    stack: 'Next.js + TS',
    description: 'Restaurant website — redesigned',
    github: 'https://github.com/MattybotStew/shanes-rib-shack-new',
    lastCommit: '2026-07-23',
    buildStatus: 'pass',
  },
  {
    name: 'Homepagev2',
    category: 'react-active',
    stack: 'Vite + React + TS',
    description: 'CMA homepage redesign with shadcn/ui',
    github: 'https://github.com/MattybotStew/Homepagev2',
    lastCommit: '2026-07-22',
    buildStatus: 'pass',
  },
  {
    name: 'oceanview',
    category: 'react-active',
    stack: 'React (Vite)',
    description: 'Property/real estate site',
    github: 'https://github.com/MattybotStew/oceanview',
    lastCommit: '2026-07-22',
    buildStatus: 'pass',
  },
  {
    name: 'ardent',
    category: 'react-active',
    stack: 'Next.js + TS',
    description: 'Early-stage Next.js project',
    github: 'https://github.com/MattybotStew/ardent',
    lastCommit: '2026-07-15',
    buildStatus: 'fail',
  },
  {
    name: 'demo-react',
    category: 'react-other',
    stack: 'Vite + React + TS',
    description: 'React demo / starter project',
    github: 'https://github.com/MattybotStew/demo-react',
    lastCommit: '2026-07-20',
    buildStatus: 'pass',
  },
  {
    name: 'Newsappheader',
    category: 'react-other',
    stack: 'Vite + React',
    description: 'News app header component',
    github: 'https://github.com/MattybotStew/Newsappheader',
    lastCommit: '2026-04-17',
    buildStatus: 'pass',
  },
  {
    name: 'penlink-homepage',
    category: 'react-other',
    stack: 'React',
    description: 'Homepage scaffold',
    github: 'https://github.com/MattybotStew/penlink-homepage',
    lastCommit: '2026-06-01',
    buildStatus: 'na',
  },
  {
    name: 'defense-lite',
    category: 'static',
    stack: 'Static HTML/CSS',
    pages: 14,
    description: 'Multi-market defense industry site',
    github: 'https://github.com/MattybotStew/defense-lite',
    live: 'https://mattybotstew.github.io/defense-lite/',
    lastCommit: '2026-07-25',
    buildStatus: 'na',
  },
  {
    name: 'microstack',
    category: 'static',
    stack: 'Static HTML/CSS',
    pages: 15,
    description: 'Microstack webflow export',
    github: 'https://github.com/MattybotStew/microstack',
    live: 'https://mattybotstew.github.io/microstack/',
    lastCommit: '2026-07-25',
    buildStatus: 'na',
  },
  {
    name: 'connected-communications-group',
    category: 'static',
    stack: 'Static HTML/CSS',
    pages: 9,
    description: 'Communications company site',
    github: 'https://github.com/MattybotStew/connected-communications-group',
    live: 'https://mattybotstew.github.io/connected-communications-group/',
    lastCommit: '2026-07-25',
    buildStatus: 'na',
  },
  {
    name: 'commercial-capital-partners',
    category: 'static',
    stack: 'Static HTML/CSS',
    pages: 8,
    description: 'Commercial capital / loan site',
    github: 'https://github.com/MattybotStew/commercial-capital-partners',
    live: 'https://mattybotstew.github.io/commercial-capital-partners/',
    lastCommit: '2026-07-25',
    buildStatus: 'na',
  },
  {
    name: 'gerotech-prototype',
    category: 'static',
    stack: 'Static HTML/CSS',
    pages: 5,
    description: 'Engineering solutions prototype',
    github: 'https://github.com/MattybotStew/gerotech-prototype',
    live: 'https://mattybotstew.github.io/gerotech-prototype/',
    lastCommit: '2026-07-16',
    buildStatus: 'na',
  },
  {
    name: 'hero',
    category: 'static',
    stack: 'Static HTML/CSS',
    pages: 1,
    description: 'Single-page hero design',
    github: 'https://github.com/MattybotStew/hero',
    live: 'https://mattybotstew.github.io/hero/',
    lastCommit: '2026-04-02',
    buildStatus: 'na',
  },
  {
    name: 'cfhf-search-prototype',
    category: 'static',
    stack: 'Static HTML/JS',
    pages: 2,
    description: 'Search prototype tool',
    github: 'https://github.com/MattybotStew/cfhf-search-prototype',
    live: 'https://mattybotstew.github.io/cfhf-search-prototype/',
    lastCommit: '2026-07-17',
    buildStatus: 'na',
  },
  {
    name: '042217-stewartwerk',
    category: 'legacy',
    stack: 'Static HTML (2017–2020)',
    description: 'Old portfolio with client wireframes',
    github: 'https://github.com/MattybotStew/042217-stewartwerk',
    lastCommit: '2020-11-02',
    buildStatus: 'na',
  },
];

export const categoryLabels: Record<Project['category'], string> = {
  'react-active': 'Active React/Next.js',
  'react-other': 'Other React Projects',
  'static': 'Static Sites (GitHub Pages)',
  'legacy': 'Legacy',
};